FirstDjangoProject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    # path("list/", views.TaskListView.as_view(), name="list"),
    path("list/", views.tasks_by_tag, name="list"),
    path("list/tag/<slug:tag_slug>", views.tasks_by_tag, name="list_by_tag"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("add-task/", views.add_task, name="api-add-task"),
    path("complete/<int:uid>", views.complete_task, name="complete"),
    path("delete/<int:uid>", views.delete_task, name="delete"),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),
    path("edit/<int:pk>", views.TaskEditView.as_view(), name="edit"),
    path("export/", views.TaskExportView.as_view(), name="export"),
]

tasks/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "High priority"),
        (PRIORITY_MEDIUM, "Medium priority"),
        (PRIORITY_LOW, "Low priority"),
    ]
    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("Performed", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tasks")
    priority = models.IntegerField(
        "Priority", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])

    tags = TaggableManager()


class TagCount(models.Model):
    tag_slug = models.CharField(max_length=128)
    tag_name = models.CharField(max_length=128)
    tag_id = models.PositiveIntegerField(default=0)
    tag_count = models.PositiveIntegerField(db_index=True, default=0)

tasks/forms.py
from django import forms

from tasks.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label='')


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description', "priority", "tags")
        labels = {'description': "Description", "priority": "", "tags": "tags"}


class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label="high priority", initial=True, required=False
    )
    prio_med = forms.BooleanField(
        label="medium priority", initial=True, required=False
    )
    prio_low = forms.BooleanField(
        label="low priority", initial=False, required=False
    )

tasks/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.db.models import Q, Count
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from taggit.models import Tag

from tasks.forms import AddTaskForm, TodoItemForm, TodoItemExportForm
from tasks.models import TodoItem

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
def index(request):
    counts = Tag.objects.annotate(
        total_tasks=Count('todoitem')
    ).order_by("-total_tasks")

    counts = {
        c.name: c.total_tasks
        for c in counts
    }

    return render(request, "tasks/index.html", {"counts": counts})


def complete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    return HttpResponse("OK")


def add_task(request):
    if request.method == "POST":
        desc = request.POST["description"]
        t = TodoItem(description=desc)
        t.save()
    return reverse("tasks:list")


def delete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.delete()
    messages.success(request, "Task was deleted")
    return redirect(reverse("tasks:list"))


def filter_tags(tags_by_tags):
    tags = []
    for lists in tags_by_tags:
        for i in lists:
            if i not in tags:
                tags.append(i)
    return tags


class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        u = self.request.user
        return u.tasks.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_tasks = self.get_queryset()
        tags = []
        for t in user_tasks:
            tags.append(list(t.tags.all()))

        context['tags'] = filter_tags(tags)
        return context


class TaskCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            form.save_m2m()
            return redirect(reverse("tasks:list"))

        return render(request, "tasks/create.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return render(request, "tasks/create.html", {"form": form})


class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'


class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect(reverse("tasks:list"))

        return render(request, "tasks/edit.html", {"form": form})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, "tasks/edit.html", {"form": form, "task": t})


class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities["prio_high"]:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = "Your tasks and priorities:\n"
        for t in list(tasks):
            if t.is_completed:
                body += f"[x] {t.description} ({t.get_priority_display()})\n"
            else:
                body += f"[ ] {t.description} ({t.get_priority_display()})\n"

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Tasks", body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, "Tasks have been sent by the e-mail %s" % email)
        else:
            messages.error(request, "Something went wrong, try again")
        return redirect(reverse("tasks:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "tasks/export.html", {"form": form})


def tasks_by_tag(request, tag_slug=None):
    u = request.user
    tasks = TodoItem.objects.filter(owner=u).all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        tasks = tasks.filter(tags__in=[tag])

    all_tags = []
    for t in tasks:
        all_tags.append(list(t.tags.all()))
    all_tags = filter_tags(all_tags)

    return render(
        request,
        "tasks/list_by_tag.html",
        {"tag": tag, "tasks": tasks, "all_tags": all_tags},
    )

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create task{% endblock %}

{% block main_content %}
    <h1>Create task</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Add</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends "base.html" %}

{% block title %}Task{{ object.id }}{% endblock %}

{#{% block extra_head %}#}
{#    <link rel="stylesheet"#}
{#          href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"#}
{#          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"#}
{#          crossorigin="anonymous">#}
{#{% endblock %}#}

{% block main_content %}
    <h1>Task</h1>
    <p><b>Description</b>: {{ object }}</p>
    <ul>
        <li>
            {{ object.is_completed|yesno:"Completed, Not completed" }}
        </li>
        <li><i class="far fa-calendar-alt"></i>&nbsp;Created: {{ object.created|date:"Y-b-d H:i" }}</li>
        <li><i class="far fa-clock"></i>&nbsp;Last update: {{ object.updated }}</li>
        <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "tasks:edit" pk=object.pk %}">Redact</a></li>
    </ul>
    <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "tasks:list" %}">Back to the list</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit task{% endblock %}

{% block main_content %}
    <h1>Edit task</h1>
    <form action="{% url "tasks:edit" task.pk %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Save</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/export.html
{% extends "base.html" %}

{% block title %}Export{% endblock %}

{% block main_content %}
    <h1>Tasks export</h1>
    <p>You will receive tasks by mail. Specify your list.</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><button class="add" type="submit">Send</button></p>
    </form>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Tags information{% endblock %}
{% block main_content %}
    <h1>Tags and numbers</h1>
    <ul>
        {% for tag, count in counts.items %}
            <li>
                <span class="badge badge-info">{{ tag }}: {{ count }}</span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Tasks for the day{% endblock %}

{% block extra_head %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block main_content %}
    <h1>Current tasks</h1>
    <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">Export by the e-mail</a></p>
    <ul id="todo-list">
        {% for task in tasks %}
            {% if task.is_completed %}
                <li class="completed">
                    <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled'
                           checked='checked'/>
                    {% else %}
                <li>
                <input class='checkbox' data-uid={{ task.id }} type='checkbox'/>
            {% endif %}
        {% if task.priority == task.PRIORITY_HIGH %}
            <span class="badge badge-pill badge-danger">&nbsp;</span>
        {% elif task.priority == task.PRIORITY_MEDIUM %}
            <span class="badge badge-pill badge-secondary">&nbsp;</span>
        {% elif task.priority == task.PRIORITY_LOW %}
            <span class="badge badge-pill badge-success">&nbsp;</span>
        {% endif %}
        <a href={% url "tasks:details" task.id %}>{{ task }}</a>
        <a class="remove" href={% url "tasks:delete" task.id %}>X</a>
        <hr/>
        </li>
        {% endfor %}
    </ul>
    <ul class="list-inline">
        {% for tag in tags %}
            <li class="list-inline-item">
                <span class="badge badge-info">{{ tag }}</span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

tasks/templates/tasks/list_by_tag.html
{% extends "base.html" %}
{% load static %}

{% block title %}Tasks for the day{% endblock %}
{% block extra_head %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}
{% block main_content %}
    {% if tag %}
        <h1>Current tasks with tag "{{ tag.name }}"</h1>
    {% else %}
        <h1>All current tasks</h1>
    {% endif %}
    <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">Export by the e-mail</a></p>
    {% for t in all_tags %}
        {% if forloop.first %}
            <ul class="list-inline">
            <li class="list-inline-item">tags:</li>
        {% endif %}
    <li class="list-inline-item">
        <a href="{% url "tasks:list_by_tag" t.slug %}">
            {% if t.pk == tag.pk %}
                <span class="badge badge-success">{{ t.name }}</span>
            {% else %}
                <span class="badge badge-info">{{ t.name }}</span>
            {% endif %}
        </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
    {% endfor %}
    <hr/>
    <ul id="todo-list">
        {% for task in tasks %}
            {% if task.is_completed %}
                <li class="completed">
                    <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled'
                           checked='checked'/>
                    {% else %}
                <li>
                <input class='checkbox' data-uid={{ task.id }} type='checkbox'/>
            {% endif %}
        {% if task.priority == task.PRIORITY_HIGH %}
            <span class="badge badge-pill badge-danger">&nbsp;</span>
        {% elif task.priority == task.PRIORITY_MEDIUM %}
            <span class="badge badge-pill badge-secondary">&nbsp;</span>
        {% elif task.priority == task.PRIORITY_LOW %}
            <span class="badge badge-pill badge-success">&nbsp;</span>
        {% endif %}
        <a href={% url "tasks:details" task.id %}>{{ task }}</a>
        <a class="remove" href={% url "tasks:delete" task.id %}>X</a>
        <hr/>
        </li>
        {% endfor %}
    </ul>
{% endblock %}